// Auto-generated gallery data
export const albums = [
  { id: 'winter-wars-1', title: 'Winter Wars 1', category: 'Winter Wars 1', color: '#FFB6C1', images: [
    "/gallery/winter-wars-1/Winter Wars 1/Champions /2nd RUNNER UP.png",
    "/gallery/winter-wars-1/Winter Wars 1/Champions /CHAMPION.png",
    "/gallery/winter-wars-1/Winter Wars 1/Champions /RUNNER UP-1.png",
    "/gallery/winter-wars-1/Winter Wars 1/Champions /RUNNER UP.png",
    "/gallery/winter-wars-1/Winter Wars 1/Coming Soon&All You Need to Know/1_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Coming Soon&All You Need to Know/2_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Coming Soon&All You Need to Know/3_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Coming Soon&All You Need to Know/4_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Coming Soon&All You Need to Know/COMING SOON.png",
    "/gallery/winter-wars-1/Winter Wars 1/Coming Soon&All You Need to Know/MAIN-4.png",
    "/gallery/winter-wars-1/Winter Wars 1/Groups/GROUP A.png",
    "/gallery/winter-wars-1/Winter Wars 1/Groups/GRP B.png",
    "/gallery/winter-wars-1/Winter Wars 1/Groups/GRP C.png",
    "/gallery/winter-wars-1/Winter Wars 1/Groups/GRP D.png",
    "/gallery/winter-wars-1/Winter Wars 1/Groups/MAIN-5.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/DAY 1 GA.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/GRAND FINALS POST-1.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/GRAND FINALS POST.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/GRAND FINALS SWIPEUP-1.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/GRAND FINALS SWIPEUP.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/GRAND FINALS THUMB.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/MATCH DAY GB_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/MATCH DAY GC_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/MATCH DAY GD_.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/MATCH DAY.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GA STORY-1.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GA STORY.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GA THUMB-1.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GA THUMB.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GA.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GB STORY.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GB THUMB.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SEMI GB.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SWIPE DAY 1 - GB.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SWIPE DAY 2 - GC.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/SWIPE DAY 2 - GD.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/THUMB GA.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/THUMB GB.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/THUMB GC.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/THUMB GD.png",
    "/gallery/winter-wars-1/Winter Wars 1/Match Day/group a-3.png",
    "/gallery/winter-wars-1/Winter Wars 1/Miscellaneous /ON AIR TALENT.png",
    "/gallery/winter-wars-1/Winter Wars 1/Miscellaneous /PROD.png",
    "/gallery/winter-wars-1/Winter Wars 1/Overall Standings/PT GRP A.png",
    "/gallery/winter-wars-1/Winter Wars 1/Overall Standings/PT GRP B.png",
    "/gallery/winter-wars-1/Winter Wars 1/Overall Standings/PT GRP C.png",
    "/gallery/winter-wars-1/Winter Wars 1/Overall Standings/PT GRP D.png",
    "/gallery/winter-wars-1/Winter Wars 1/Overall Standings/SEMI FINALS PT 2.png",
    "/gallery/winter-wars-1/Winter Wars 1/Overall Standings/SEMI FINALS PT_.png",
  ] },
  { id: 'winter-wars-2', title: 'Winter Wars 2', category: 'Winter Wars 2', color: '#FF00FF', images: [
    "/gallery/winter-wars-2/Winter Wars 2/All you need to know/1.png",
    "/gallery/winter-wars-2/Winter Wars 2/All you need to know/2_-1.png",
    "/gallery/winter-wars-2/Winter Wars 2/All you need to know/4.png",
    "/gallery/winter-wars-2/Winter Wars 2/All you need to know/MAIN-7.png",
    "/gallery/winter-wars-2/Winter Wars 2/Champions/CHAMP MALE.png",
    "/gallery/winter-wars-2/Winter Wars 2/Champions/Champions 2.png",
    "/gallery/winter-wars-2/Winter Wars 2/Champions/Champions.png",
    "/gallery/winter-wars-2/Winter Wars 2/Champions/MVP male.png",
    "/gallery/winter-wars-2/Winter Wars 2/Champions/MVP.png",
    "/gallery/winter-wars-2/Winter Wars 2/Match Day/GRAND FINALS POST GIRLS_.png",
    "/gallery/winter-wars-2/Winter Wars 2/Match Day/GRAND FINALS POST-2.png",
    "/gallery/winter-wars-2/Winter Wars 2/Match Day/GRAND FINALS SWIPEUP GIRLS_.png",
    "/gallery/winter-wars-2/Winter Wars 2/Match Day/GRAND FINALS SWIPEUP-2.png",
    "/gallery/winter-wars-2/Winter Wars 2/Match Day/GRAND FINALS THUMB GIRLS_.png",
    "/gallery/winter-wars-2/Winter Wars 2/Match Day/GRAND FINALS THUMB-1.png",
    "/gallery/winter-wars-2/Winter Wars 2/Overall Standings/OS MALE.png",
    "/gallery/winter-wars-2/Winter Wars 2/Overall Standings/OVERALL STANDING.png",
    "/gallery/winter-wars-2/Winter Wars 2/Overall Standings/PT GIRLS GROUP-1.png",
    "/gallery/winter-wars-2/Winter Wars 2/Overall Standings/PT GIRLS GROUP.png"
  ] }
];
